package ch.framedev.lagersystem.managers;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.ResultSet;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration-style unit tests for {@link DatabaseManager} using an H2 file database
 * in a temporary directory, so the tests are self-contained and leave no permanent artefacts.
 */
class DatabaseManagerTest {

    private Path tempDir;
    private DatabaseManager db;

    @BeforeEach
    void setUp() throws IOException {
        // Arrange: create a fresh H2 database in a temp dir for each test
        tempDir = Files.createTempDirectory("vebo-db-test-");
        db = new DatabaseManager(DatabaseManager.DatabaseType.H2, tempDir.toString(), "testdb");
        db.initializeApplicationSchema();
    }

    @AfterEach
    void tearDown() throws IOException {
        if (db != null) {
            db.close();
        }
        // Clean up temp directory (recursive)
        if (tempDir != null && Files.exists(tempDir)) {
            try (Stream<Path> walk = Files.walk(tempDir)) {
                walk.sorted(Comparator.reverseOrder())
                        .map(Path::toFile)
                        .forEach(java.io.File::delete);
            }
        }
    }

    // =========================================================================
    // Basic type checks
    // =========================================================================

    @Test
    @DisplayName("isSQLite: false for H2 database")
    void isSQLite_falseForH2() {
        assertFalse(db.isSQLite());
    }

    @Test
    @DisplayName("isH2: true for H2 database")
    void isH2_trueForH2() {
        assertTrue(db.isH2());
    }

    @Test
    @DisplayName("isFilesystemBackend: false for H2 database")
    void isFilesystemBackend_falseForH2() {
        assertFalse(db.isFilesystemBackend());
    }

    @Test
    @DisplayName("JSON filesystem backend writes schema version manifest")
    void jsonFilesystemBackend_writesSchemaVersionManifest() throws IOException {
        DatabaseManager jsonDb = new DatabaseManager(DatabaseManager.DatabaseType.JSON,
                tempDir.toString(), "schema-test");
        try {
            jsonDb.initializeApplicationSchema();

            Path schemaFile = tempDir.resolve("schema-test_json").resolve("schema.json");
            assertTrue(Files.exists(schemaFile), "JSON schema manifest should exist");
            assertEquals(1, jsonDb.getFilesystemSchemaVersion());
            assertTrue(Files.readString(schemaFile).contains("\"schemaVersion\": 1"));
        } finally {
            jsonDb.close();
        }
    }

    @Test
    @DisplayName("YAML filesystem backend writes schema version manifest")
    void yamlFilesystemBackend_writesSchemaVersionManifest() throws IOException {
        DatabaseManager yamlDb = new DatabaseManager(DatabaseManager.DatabaseType.YAML,
                tempDir.toString(), "schema-test");
        try {
            yamlDb.initializeApplicationSchema();

            Path schemaFile = tempDir.resolve("schema-test_yaml").resolve("schema.yaml");
            assertTrue(Files.exists(schemaFile), "YAML schema manifest should exist");
            assertEquals(1, yamlDb.getFilesystemSchemaVersion());
            assertTrue(Files.readString(schemaFile).contains("schemaVersion: 1"));
        } finally {
            yamlDb.close();
        }
    }

    @Test
    @DisplayName("getDatabaseType: returns H2")
    void getDatabaseType_h2() {
        assertEquals(DatabaseManager.DatabaseType.H2, db.getDatabaseType());
    }

    @Test
    @DisplayName("getDatabaseUrl: contains 'h2:file'")
    void getDatabaseUrl_containsH2File() {
        assertTrue(db.getDatabaseUrl().contains("h2:file"),
                "Expected H2 file URL but got: " + db.getDatabaseUrl());
    }

    // =========================================================================
    // identityColumn()
    // =========================================================================

    @Test
    @DisplayName("identityColumn: H2 uses GENERATED BY DEFAULT AS IDENTITY")
    void identityColumn_h2_usesGeneratedIdentity() {
        String col = db.identityColumn("id");
        assertTrue(col.contains("GENERATED BY DEFAULT AS IDENTITY"),
                "H2 identity column must use GENERATED BY DEFAULT syntax");
    }

    // =========================================================================
    // listUserTables() after initializeApplicationSchema()
    // =========================================================================

    @Test
    @DisplayName("listUserTables: all application tables exist after schema init")
    void listUserTables_allExpectedTables() {
        List<String> tables = db.listUserTables();
        // Check that at least the core application tables are present (case-insensitive)
        assertTrue(tables.stream().anyMatch(t -> t.equalsIgnoreCase(DatabaseManager.TABLE_ARTICLES)),
                "Missing table: " + DatabaseManager.TABLE_ARTICLES);
        assertTrue(tables.stream().anyMatch(t -> t.equalsIgnoreCase(DatabaseManager.TABLE_VENDORS)),
                "Missing table: " + DatabaseManager.TABLE_VENDORS);
        assertTrue(tables.stream().anyMatch(t -> t.equalsIgnoreCase(DatabaseManager.TABLE_DEPARTMENTS)),
                "Missing table: " + DatabaseManager.TABLE_DEPARTMENTS);
        assertTrue(tables.stream().anyMatch(t -> t.equalsIgnoreCase(DatabaseManager.TABLE_ORDERS)),
                "Missing table: " + DatabaseManager.TABLE_ORDERS);
        assertTrue(tables.stream().anyMatch(t -> t.equalsIgnoreCase(DatabaseManager.TABLE_CLIENTS)),
                "Missing table: " + DatabaseManager.TABLE_CLIENTS);
        assertTrue(tables.stream().anyMatch(t -> t.equalsIgnoreCase(DatabaseManager.TABLE_LOGS)),
                "Missing table: " + DatabaseManager.TABLE_LOGS);
    }

    // =========================================================================
    // getTableColumns()
    // =========================================================================

    @Test
    @DisplayName("getTableColumns: departments table has expected columns")
    void getTableColumns_departmentsTable() {
        List<String> columns = db.getTableColumns(DatabaseManager.TABLE_DEPARTMENTS);
        assertFalse(columns.isEmpty(), "Column list must not be empty");
        assertTrue(columns.stream().anyMatch(c -> c.equalsIgnoreCase("departmentName")),
                "Expected 'departmentName' column");
        assertTrue(columns.stream().anyMatch(c -> c.equalsIgnoreCase("kontoNumber")),
                "Expected 'kontoNumber' column");
    }

    @Test
    @DisplayName("getTableColumns: null tableName returns empty list")
    void getTableColumns_null_returnsEmpty() {
        List<String> columns = db.getTableColumns(null);
        assertTrue(columns.isEmpty());
    }

    @Test
    @DisplayName("getTableColumns: blank tableName returns empty list")
    void getTableColumns_blank_returnsEmpty() {
        List<String> columns = db.getTableColumns("   ");
        assertTrue(columns.isEmpty());
    }

    // =========================================================================
    // executeTrustedUpdate / executeTrustedQuery
    // =========================================================================

    @Test
    @DisplayName("executeTrustedUpdate: INSERT succeeds and data is queryable")
    void executeTrustedUpdate_insertAndQuery() throws Exception {
        // Arrange
        String insertSql = "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS
                + " (departmentName, kontoNumber) VALUES ('TestAbteilung', '9999')";

        // Act
        boolean result = db.executeTrustedUpdate(insertSql);

        // Assert insert succeeded
        assertTrue(result);

        // Verify data was stored
        ResultSet rs = db.executeTrustedQuery(
                "SELECT departmentName FROM " + DatabaseManager.TABLE_DEPARTMENTS
                        + " WHERE departmentName = 'TestAbteilung'");
        assertNotNull(rs);
        try {
            assertTrue(rs.next(), "Expected at least one row");
            assertEquals("TestAbteilung", rs.getString("departmentName"));
        } finally {
            db.closeQuery(rs);
        }
    }

    @Test
    @DisplayName("executeTrustedUpdate: empty SQL returns false")
    void executeTrustedUpdate_emptySql_returnsFalse() {
        assertFalse(db.executeTrustedUpdate(""));
        assertFalse(db.executeTrustedUpdate(null));
    }

    // =========================================================================
    // executePreparedUpdate / executeQuery(sql, params)
    // =========================================================================

    @Test
    @DisplayName("executePreparedUpdate: parameterised INSERT and SELECT")
    void executePreparedUpdate_insertAndSelect() throws Exception {
        // Arrange
        String insertSql = "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS
                + " (departmentName, kontoNumber) VALUES (?, ?)";

        // Act
        boolean result = db.executePreparedUpdate(insertSql,
                new Object[]{"ParamAbteilung", "1234"});

        // Assert
        assertTrue(result, "Prepared INSERT should succeed");

        // Verify with prepared query
        ResultSet rs = db.executeQuery(
                "SELECT kontoNumber FROM " + DatabaseManager.TABLE_DEPARTMENTS
                        + " WHERE departmentName = ?",
                "ParamAbteilung");
        assertNotNull(rs);
        try {
            assertTrue(rs.next(), "Expected one row");
            assertEquals("1234", rs.getString("kontoNumber"));
        } finally {
            db.closeQuery(rs);
        }
    }

    // =========================================================================
    // queryList / queryOne
    // =========================================================================

    @Test
    @DisplayName("queryList: returns correct number of mapped rows")
    void queryList_returnsMappedRows() {
        // Arrange: insert two departments
        db.executePreparedUpdate(
                "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS + " (departmentName, kontoNumber) VALUES (?,?)",
                new Object[]{"Dept1", "111"});
        db.executePreparedUpdate(
                "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS + " (departmentName, kontoNumber) VALUES (?,?)",
                new Object[]{"Dept2", "222"});

        // Act
        List<String> names = db.queryList(
                "SELECT departmentName FROM " + DatabaseManager.TABLE_DEPARTMENTS + " ORDER BY departmentName",
                null,
                rs -> {
                    try {
                        return rs.getString("departmentName");
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                });

        // Assert
        assertEquals(2, names.size());
        assertTrue(names.contains("Dept1"));
        assertTrue(names.contains("Dept2"));
    }

    @Test
    @DisplayName("queryOne: returns first row or null when empty")
    void queryOne_returnsFirstRowOrNull() {
        // Empty table → null
        String result = db.queryOne(
                "SELECT departmentName FROM " + DatabaseManager.TABLE_DEPARTMENTS,
                null,
                rs -> {
                    try {
                        return rs.getString("departmentName");
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                });
        assertNull(result, "Empty table should return null");

        // After insert → returns value
        db.executePreparedUpdate(
                "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS + " (departmentName, kontoNumber) VALUES (?,?)",
                new Object[]{"OnlyDept", "999"});

        String found = db.queryOne(
                "SELECT departmentName FROM " + DatabaseManager.TABLE_DEPARTMENTS,
                null,
                rs -> {
                    try {
                        return rs.getString("departmentName");
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                });
        assertEquals("OnlyDept", found);
    }

    // =========================================================================
    // clearTable()
    // =========================================================================

    @Test
    @DisplayName("clearTable: valid table name clears all rows")
    void clearTable_validTable_clearsRows() throws Exception {
        // Arrange
        db.executePreparedUpdate(
                "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS + " (departmentName, kontoNumber) VALUES (?,?)",
                new Object[]{"ClearDept", "000"});

        // Act
        boolean result = db.clearTable(DatabaseManager.TABLE_DEPARTMENTS);

        // Assert
        assertTrue(result);
        ResultSet rs = db.executeTrustedQuery(
                "SELECT COUNT(*) FROM " + DatabaseManager.TABLE_DEPARTMENTS);
        assertNotNull(rs);
        try {
            assertTrue(rs.next());
            assertEquals(0, rs.getInt(1));
        } finally {
            db.closeQuery(rs);
        }
    }

    @Test
    @DisplayName("clearTable: null table name returns false")
    void clearTable_null_returnsFalse() {
        assertFalse(db.clearTable(null));
    }

    @Test
    @DisplayName("clearTable: blank table name returns false")
    void clearTable_blank_returnsFalse() {
        assertFalse(db.clearTable("   "));
    }

    @Test
    @DisplayName("clearTable: unauthorized table name returns false (SQL injection guard)")
    void clearTable_unauthorizedTable_returnsFalse() {
        assertFalse(db.clearTable("system_tables"));
        assertFalse(db.clearTable("unknown_table"));
    }

    // =========================================================================
    // dropTableIfExists()
    // =========================================================================

    @Test
    @DisplayName("dropTableIfExists: safe identifier is dropped successfully")
    void dropTableIfExists_safeIdentifier_succeeds() throws Exception {
        // Arrange: create a temp table
        db.executeTrustedUpdate("CREATE TABLE IF NOT EXISTS temp_test_table (id INTEGER, name TEXT)");
        assertTrue(db.listUserTables().stream()
                .anyMatch(t -> t.equalsIgnoreCase("temp_test_table")));

        // Act
        boolean result = db.dropTableIfExists("temp_test_table");

        // Assert
        assertTrue(result);
        assertFalse(db.listUserTables().stream()
                .anyMatch(t -> t.equalsIgnoreCase("temp_test_table")),
                "Table should have been dropped");
    }

    @Test
    @DisplayName("dropTableIfExists: unsafe name (contains spaces) returns false")
    void dropTableIfExists_unsafeName_returnsFalse() {
        assertFalse(db.dropTableIfExists("bad table name"));
        assertFalse(db.dropTableIfExists("table;DROP TABLE users"));
    }

    @Test
    @DisplayName("dropTableIfExists: null/blank returns false")
    void dropTableIfExists_nullOrBlank_returnsFalse() {
        assertFalse(db.dropTableIfExists(null));
        assertFalse(db.dropTableIfExists("  "));
    }

    // =========================================================================
    // clearDatabase()
    // =========================================================================

    @Test
    @DisplayName("clearDatabase: removes all rows from all application tables")
    void clearDatabase_removesAllData() throws Exception {
        // Arrange: insert data into several tables
        db.executePreparedUpdate(
                "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS + " (departmentName, kontoNumber) VALUES (?,?)",
                new Object[]{"D1", "1"});
        db.executePreparedUpdate(
                "INSERT INTO " + DatabaseManager.TABLE_VENDORS
                        + " (name, contactPerson, phoneNumber, email, address, suppliedArticles, minOrderValue) VALUES (?,?,?,?,?,?,?)",
                new Object[]{"Vendor1", "Hans", "0800", "v@v.ch", "Strasse", "A1,A2", 100.0});

        // Act
        boolean result = db.clearDatabase();

        // Assert
        assertTrue(result, "clearDatabase must return true on success");

        ResultSet rs1 = db.executeTrustedQuery(
                "SELECT COUNT(*) FROM " + DatabaseManager.TABLE_DEPARTMENTS);
        assertNotNull(rs1);
        try {
            assertTrue(rs1.next());
            assertEquals(0, rs1.getInt(1), "Departments table must be empty");
        } finally {
            db.closeQuery(rs1);
        }
        ResultSet rs2 = db.executeTrustedQuery(
                "SELECT COUNT(*) FROM " + DatabaseManager.TABLE_VENDORS);
        assertNotNull(rs2);
        try {
            assertTrue(rs2.next());
            assertEquals(0, rs2.getInt(1), "Vendors table must be empty");
        } finally {
            db.closeQuery(rs2);
        }
    }

    // =========================================================================
    // SQL injection guard in deprecated executeQuery(String) and executeUpdate(String)
    // =========================================================================

    @Test
    @DisplayName("deprecated executeQuery: multi-statement with semicolon is rejected")
    @SuppressWarnings("deprecation")
    void executeQuery_deprecated_multiStatement_rejected() {
        // Semicolon followed by non-whitespace indicates a second statement
        ResultSet rs = db.executeQuery(
                "SELECT * FROM " + DatabaseManager.TABLE_DEPARTMENTS + "; DROP TABLE users");
        assertNull(rs, "Multi-statement SQL must be rejected by the safety guard");
    }

    @Test
    @DisplayName("deprecated executeQuery: SQL comment pattern is rejected")
    @SuppressWarnings("deprecation")
    void executeQuery_deprecated_sqlComment_rejected() {
        ResultSet rs = db.executeQuery(
                "SELECT * FROM " + DatabaseManager.TABLE_DEPARTMENTS + " -- comment");
        assertNull(rs, "SQL comment injection must be rejected");
    }

    @Test
    @DisplayName("deprecated executeUpdate: SQL with comment is rejected")
    @SuppressWarnings("deprecation")
    void executeUpdate_deprecated_sqlComment_rejected() {
        boolean result = db.executeUpdate(
                "DELETE FROM " + DatabaseManager.TABLE_DEPARTMENTS + " -- comment");
        assertFalse(result, "SQL with comment must be rejected");
    }

    // =========================================================================
    // inTransaction()
    // =========================================================================

    @Test
    @DisplayName("inTransaction: work block is committed on success")
    void inTransaction_committed_onSuccess() throws Exception {
        // Act
        boolean result = db.inTransaction(conn -> {
            try (var stmt = conn.prepareStatement(
                    "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS
                            + " (departmentName, kontoNumber) VALUES (?, ?)")) {
                stmt.setObject(1, "TxDept");
                stmt.setObject(2, "TX1");
                stmt.executeUpdate();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });

        // Assert
        assertTrue(result, "Transaction must commit successfully");
        ResultSet rs = db.executeTrustedQuery(
                "SELECT COUNT(*) FROM " + DatabaseManager.TABLE_DEPARTMENTS
                        + " WHERE departmentName = 'TxDept'");
        assertNotNull(rs);
        try {
            assertTrue(rs.next());
            assertEquals(1, rs.getInt(1));
        } finally {
            db.closeQuery(rs);
        }
    }

    @Test
    @DisplayName("inTransaction: unchecked exception propagates to caller (inTransaction only catches SQLException)")
    void inTransaction_runtimeException_propagatesToCaller() {
        // The Consumer<Connection> interface cannot throw checked exceptions.
        // inTransaction() only catches SQLException, so RuntimeException propagates
        // through and is NOT silently swallowed — the caller receives it.
        assertThrows(RuntimeException.class, () ->
                db.inTransaction(conn -> {
                    try (var stmt = conn.prepareStatement(
                            "INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS
                                    + " (departmentName, kontoNumber) VALUES (?, ?)")) {
                        stmt.setObject(1, "PropagatedDept");
                        stmt.setObject(2, "RB1");
                        stmt.executeUpdate();
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                    // Force an unchecked exception to verify propagation behaviour
                    throw new RuntimeException("Simulated failure");
                })
        );
    }

    // =========================================================================
    // executeTrustedUpdateWithCount
    // =========================================================================

    @Test
    @DisplayName("executeTrustedUpdateWithCount: returns correct affected row count")
    void executeTrustedUpdateWithCount_returnsCount() {
        // Arrange
        db.executeTrustedUpdate("INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS
                + " (departmentName, kontoNumber) VALUES ('CountDept1', '1')");
        db.executeTrustedUpdate("INSERT INTO " + DatabaseManager.TABLE_DEPARTMENTS
                + " (departmentName, kontoNumber) VALUES ('CountDept2', '2')");

        // Act
        int count = db.executeTrustedUpdateWithCount(
                "DELETE FROM " + DatabaseManager.TABLE_DEPARTMENTS
                        + " WHERE departmentName LIKE 'CountDept%'");

        // Assert
        assertEquals(2, count, "Two rows should have been deleted");
    }

    @Test
    @DisplayName("executeTrustedUpdateWithCount: empty SQL returns -1")
    void executeTrustedUpdateWithCount_emptySql_returnsNegativeOne() {
        assertEquals(-1, db.executeTrustedUpdateWithCount(""));
        assertEquals(-1, db.executeTrustedUpdateWithCount(null));
    }
}

